name: DeleteMe

options:
  xcodeVersion: '9999'

configs:
  Debug: debug
  Release: release
  
targets:
  DeleteMe:
    type: framework
    platform: iOS
    bundleIdPrefix: dev.pastre.learningjourney
    settings:
      base:
        INFOPLIST_FILE: DeleteMe/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: dev.pastre.learningjourney.DeleteMe
    sources: DeleteMe

  DeleteMeTests:
    type: bundle.unit-test
    platform: iOS
    bundleIdPrefix: dev.pastre.learningjourney
    settings:
      base:
        INFOPLIST_FILE: DeleteMeTests/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: dev.pastre.learningjourney.DeleteMeTests
    sources:
      - path: DeleteMeTests

    dependencies:
      - target: DeleteMe

  DeleteMeSample:
    type: application
    platform: iOS
    sources: DeleteMeSample
    settings:
      base:
        INFOPLIST_FILE: DeleteMeSample/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: dev.pastre.learningjourney.DeleteMeSample
    dependencies:
      - target: DeleteMe
        embed: false

schemes:
  DeleteMeSample:
    build:
        targets:
            DeleteMeSample: all
    run:
        targets:
            DeleteMeSample: all
  DeleteMe:
    build:
      targets:
        DeleteMe: all
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: DeleteMeTests
          parallelizable: true
          randomExecutionOrder: true
