name: <module_name>

options:
  xcodeVersion: '9999'

configs:
  Debug: debug
  Homolog: release
  Release: release
  Wiremock: debug
configFiles:
  Debug: Configs/BaseDebug.xcconfig
  Homolog: Configs/BaseHomolog.xcconfig
  Release: Configs/BaseRelease.xcconfig
  Wiremock: Configs/BaseWiremock.xcconfig
  
targets:
  <module_name>:
    type: framework
    platform: iOS

    configFiles:
      Debug: Configs/TargetDebug.xcconfig
      Homolog: Configs/TargetHomolog.xcconfig
      Release: Configs/TargetRelease.xcconfig
      Wiremock: Configs/TargetWiremock.xcconfig

    sources:
      - path: <module_name>
        excludes:
          - "**/*.md"
    
    dependencies:
      - framework: <module_name>Interface.framework
        implicit: true

    preBuildScripts:
      - script: '[ -f ./swiftgen.yml ] && swiftgen || echo "No swiftgen.yml found"'
        name: SwiftGen
      - path: ../../Scripts/SwiftLint.sh
        name: SwiftLint
      - path: ../../Scripts/SwiftLint-modules.sh
        name: Interface Modules Only


  <module_name>Tests:
    type: bundle.unit-test
    platform: iOS

    configFiles:
      Debug: Configs/UnitTestsDebug.xcconfig
      Homolog: Configs/UnitTestsHomolog.xcconfig
      Release: Configs/UnitTestsRelease.xcconfig
      Wiremock: Configs/UnitTestsWiremock.xcconfig

    sources:
      - path: <module_name>Tests

    dependencies:
      - target: <module_name>
      - target: <module_name>Sample
    
  <module_name>FunctionalTests:
    type: bundle.unit-test
    platform: iOS

    configFiles:
      Debug: Configs/FunctionalTestsDebug.xcconfig
      Homolog: Configs/FunctionalTestsHomolog.xcconfig
      Release: Configs/FunctionalTestsRelease.xcconfig
      Wiremock: Configs/FunctionalTestsWiremock.xcconfig

    sources:
        - path: <module_name>FunctionalTests

    dependencies:
      - target: <module_name>
        embed: false
      - target: <module_name>Sample    
        embed: false

  <module_name>Sample:
    type: application
    platform: iOS
    sources: [<module_name>Sample]
    configFiles:
      Debug: <module_name>Sample/Configs/<module_name>SampleDebug.xcconfig
      Homolog: <module_name>Sample/Configs/<module_name>SampleHomolog.xcconfig
      Release: <module_name>Sample/Configs/<module_name>SampleRelease.xcconfig
      Wiremock: <module_name>Sample/Configs/<module_name>SampleWiremock.xcconfig        

    dependencies:
      - target: <module_name>

schemes:
  <module_name>:
    build:
      targets:
        <module_name>: all
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: <module_name>Tests
          parallelizable: false
          randomExecutionOrder: true
        - name: <module_name>FunctionalTests
          parallelizable: false
          randomExecutionOrder: true