name: CoreTracking

options:
  xcodeVersion: '9999'

configs:
  Debug: debug
  Release: release
  
targets:
  CoreTracking:
    type: framework
    platform: iOS
    bundleIdPrefix: dev.pastre.learningjourneyapp
    settings:
      base:
        INFOPLIST_FILE: CoreTracking/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: dev.pastre.learningjourneyapp.CoreTracking
    sources: CoreTracking
    dependencies:
      - package: FirebaseAnalytics

  CoreTrackingTests:
    type: bundle.unit-test
    platform: iOS
    bundleIdPrefix: dev.pastre.learningjourneyapp
    settings:
      base:
        INFOPLIST_FILE: CoreTrackingTests/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: dev.pastre.learningjourneyapp.CoreTrackingTests
    sources:
      - path: CoreTrackingTests

    dependencies:
      - target: CoreTracking

  CoreTrackingSample:
    type: application
    platform: iOS
    sources: CoreTrackingSample
    settings:
      base:
        INFOPLIST_FILE: CoreTrackingSample/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: dev.pastre.learningjourneyapp.CoreTrackingSample
    dependencies:
      - target: CoreTracking
        embed: false

schemes:
  CoreTrackingSample:
    build:
        targets:
            CoreTrackingSample: all
    run:
        targets:
            CoreTrackingSample: all
  CoreTracking:
    build:
      targets:
        CoreTracking: all
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: CoreTrackingTests
          parallelizable: true
          randomExecutionOrder: true
    
packages:
  FirebaseAnalytics:
    url: https://github.com/firebase/firebase-ios-sdk.git
    version: 8.10.0
