name: TestingUtils

options:
  xcodeVersion: '9999'

configs:
  Debug: debug
  Release: release

targets:
  TestingUtils:
    type: framework
    platform: iOS
    bundleIdPrefix: dev.pastre.learningjourneyapp
    settings:
      base:
        INFOPLIST_FILE: TestingUtils/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: dev.pastre.learningjourneyapp.TestingUtils
    sources: TestingUtils

  TestingUtilsSample:
    type: application
    platform: iOS
    sources: TestingUtilsSample
    settings:
      base:
        INFOPLIST_FILE: TestingUtilsSample/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: dev.pastre.learningjourneyapp.TestingUtilsSample
    dependencies:
      - target: TestingUtils
        embed: false

schemes:
  TestingUtilsSample:
    build:
        targets:
            TestingUtilsSample: all
    run:
        targets:
            TestingUtilsSample: all
  TestingUtils:
    build:
      targets:
        TestingUtils: all
