source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'
use_frameworks! :linkage => :static

workspace 'LearningJourney'

# Firebase pods group
def firebase_pods
    pod 'Firebase/Analytics'
end

# App target
target 'LearningJourney' do
    project 'App/LearningJourney.project'
end

## Core modules
target 'CoreAdapters' do
    project 'Modules/Core/CoreAdapters/CoreAdapters.project'

    target 'CoreAdaptersSample' do
        # Sample target dependencies
        inherit! :complete
        platform :ios, '13.0'
    end

    target 'CoreAdaptersTests' do
        # Test target dependencies
        inherit! :search_paths
    end
end

target 'CoreAnalytics' do
    project 'Modules/Core/CoreAnalytics/CoreAnalytics.project'

    firebase_pods

    target 'CoreAnalyticsSample' do
        # Sample target dependencies
        inherit! :complete
        platform :ios, '13.0'
    end

    target 'CoreAnalyticsTests' do
        # Test target dependencies
        inherit! :search_paths
    end
end

target 'CoreAuthentication' do
    project 'Modules/Core/CoreAuthentication/CoreAuthentication.project'

    target 'CoreAuthenticationSample' do
        # Sample target dependencies
        inherit! :complete
        platform :ios, '13.0'
    end

    target 'CoreAuthenticationTests' do
        # Test target dependencies
        inherit! :search_paths
    end
end

target 'CoreEnvironment' do
    project 'Modules/Core/CoreEnvironment/CoreEnvironment.project'

    target 'CoreEnvironmentSample' do
        # Sample target dependencies
        inherit! :complete
        platform :ios, '13.0'
    end

    target 'CoreEnvironmentTests' do
        # Test target dependencies
        inherit! :search_paths
    end

end

target 'CoreInjector' do
    project 'Modules/Core/CoreInjector/CoreInjector.project'

    target 'CoreInjectorSample' do
        # Sample target dependencies
        inherit! :complete
        platform :ios, '13.0'
    end

    target 'CoreInjectorTests' do
        # Test target dependencies
        inherit! :search_paths
    end
end

target 'CoreNetworking' do
    project 'Modules/Core/CoreNetworking/CoreNetworking.project'

    target 'CoreNetworkingSample' do
        # Sample target dependencies
        inherit! :complete
        platform :ios, '13.0'
    end

    target 'CoreNetworkingTests' do
        # Test target dependencies
        inherit! :search_paths
    end
end

target 'TestingUtils' do
    project 'Modules/Core/TestingUtils/TestingUtils.project'
end

target 'UI' do
    project 'Modules/Core/UI/UI.project'

    target 'UISample' do
        # Sample target dependencies
        inherit! :complete
        platform :ios, '13.0'
    end

    target 'UITests' do
        # Test target dependencies
        inherit! :search_paths
    end
end

## Feature modules

target 'JLibrary' do
    project 'Modules/Features/JLibrary/JLibrary.project'

    target 'JLibrarySample' do
        # Sample target dependencies
        inherit! :complete
        platform :ios, '13.0'
    end

    target 'JLibraryTests' do
        # Test target dependencies
        inherit! :search_paths
    end
end

target 'JAuthentication' do

    project 'Modules/Features/JAuthentication/JAuthentication.project'

    target 'JAuthenticationSample' do
        # Sample target dependencies
        inherit! :complete
        platform :ios, '13.0'
    end

    target 'JAuthenticationTests' do
        # Test target dependencies
        inherit! :search_paths
    end
end